
spring:
  application:
    name: dispatch-service
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: ${spring.application.name}
          content-type: application/json
        packlabel-out-0:
          destination: order-dispatched
          content-type: application/json
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 2s
server:
  port: 3004
