server:
  port: 3000
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5


spring:
  mvc:
    servlet:
      path: "/api/v1"
  profiles:
    active: test-data

polar:
  greeting: Welcome to polar books cloud native