services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - catalog-network
    restart: unless-stopped

  catalog-service:
    depends_on:
      - postgres
    image: zena07/catalog-service:latest
    container_name: catalog-service
    ports:
      - "3000:3000"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-network:5432/catalog
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001


networks:
  catalog-network:
    driver: bridge

volumes:
  postgres:

