version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata  # Adjusted to standard PGDATA path
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - catalog-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-admin}"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - catalog-network  # Corrected network name
    restart: unless-stopped

  polar-redis:
    image: "redis:latest"
    container_name: "polar_redis"
    ports:
      - "6379:6379"

  catalog-service:
    depends_on:
      - postgres
    image: zena07/catalog-service:latest
    container_name: catalog-service
    ports:
      - "3000:3000"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/catalog
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
    networks:
      - catalog-network
    restart: unless-stopped

  config-service:
    image: zena07/config-server:latest
    container_name: config-service
    ports:
      - "8888:8888"
      - "9888:9888"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888
    networks:
      - catalog-network
    restart: unless-stopped

  polar-rabbitmq:
    image: rabbitmq:latest
    container_name: polar-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - catalog-network

  polar-keycloak:
    image: quay.io/keycloak/keycloak:26.0.4
    container_name: "polar-keycloak"
    volumes:
      - ./keycloak:/opt/keycloak/imports
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_IMPORT=/opt/keycloak/imports/realm-config.json
    command: [ "start-dev" ]
    ports:
      - "8080:8080"
    networks:
      - catalog-network





networks:
  catalog-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
