server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zena4L/config-repo
          clone-on-start: true
          force-pull: true
          timeout: 5