name: CI Pipeline

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Grant execute permissions for Maven wrapper
        run: |
          chmod +x ./catalog-service/mvnw

      - name: Build the project
        working-directory: ./catalog-service
        run: |
          ./mvnw clean install
