name: CI Pipeline

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Step to build `config-server` first
      - name: Grant execute permissions for Maven wrapper (config-server)
        run: chmod +x ./config-server/mvnw

      - name: Build config-server
        working-directory: ./config-server
        run: ./mvnw clean install

      # Step to build `book-catalog` after `config-server`
      - name: Grant execute permissions for Maven wrapper (book-catalog)
        run: chmod +x ./book-catalog/mvnw

      - name: Build book-catalog
        working-directory: ./book-catalog
        run: ./mvnw clean install
