name: CI Pipeline

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Build and Start Config Server
      - name: Grant execute permissions for Maven wrapper (config-server)
        run: chmod +x ./config-server/mvnw

      - name: Build config-server
        working-directory: ./config-server
        run: ./mvnw clean install

      - name: Start config-server
        working-directory: ./config-server
        run: |
          nohup ./mvnw spring-boot:run &
          sleep 10 # Wait for the server to start

      # Verify Config Server Availability
#      - name: Wait for config-server to be available
#        run: |
#          until $(curl --output /dev/null --silent --head --fail http://localhost:8888); do
#            echo "Waiting for config-server..."
#            sleep 5
#          done
#        timeout-minutes: 1

      # Build Book Catalog Service
      - name: Grant execute permissions for Maven wrapper (book-catalog)
        run: chmod +x ./book-catalog/mvnw

      - name: Build book-catalog
        working-directory: ./book-catalog
        run: ./mvnw clean install
